apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  lineConfigLineLoginRedirectUri: {{ .Values.secret.data.lineConfigLineLoginRedirectUri | b64enc }}
  lineConfigLineLoginSecretId: {{ .Values.secret.data.lineConfigLineLoginSecretId | b64enc }}
  lineConfigLineLoginClientId: {{ .Values.secret.data.lineConfigLineLoginClientId | b64enc }}