apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  defaultUser: {{ .Values.secret.data.defaultUser | b64enc }}
  {{- if eq .Release.Namespace "lmc-dev" }}
  defaultPass: {{ index .Values.secret.data.defaultPass 1 | b64enc }}
  hostName: {{ index .Values.secret.data.hostName 1 | b64enc }}
  {{- else }}
  defaultPass: {{ index .Values.secret.data.defaultPass 0 | b64enc }}
  hostName: {{ index .Values.secret.data.hostName 0 | b64enc }}
  {{- end}}