apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  defaultUser: {{ .Values.global.secrets.defaultUser | b64enc }}
  defaultPass: {{ .Values.global.secrets.defaultPass | b64enc }}
  hostName: {{ .Values.secret.data.hostName | b64enc }}