apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec: 
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.ports.amqp }} 
      name: amqp
      targetPort: {{ .Values.service.ports.amqp }} 
      {{- if eq .Release.Namespace "default" }}
      nodePort: {{ .Values.service.ports.nodePort }} 
      {{- end }}
    - port: {{ .Values.service.ports.management }}
      name: management
      targetPort: {{ .Values.service.ports.management }}
  {{- if eq .Release.Namespace "dev" }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}