apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec: 
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.ports.amqp }} 
      name: amqp
      targetPort: {{ .Values.service.ports.amqp }} 
      nodePort: {{ .Values.service.ports.nodePort }} 
    - port: {{ .Values.service.ports.management }}
      name: management
      targetPort: {{ .Values.service.ports.management }}

  type: {{ .Values.service.type }}