apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lmc-api-message-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    # nginx.ingress.kubernetes.io/use-reges: 'true'
spec:
  tls:
  - hosts:
    - {{ index .Values.ingress.rules 0 "host" }}
    secretName: lmc-api-message-tls
  rules:
  - host: {{ index .Values.ingress.rules 0 "host" }}
    http:
      paths:
      - pathType: Prefix
        path: "/message"
        backend:
          service:
            name: lmc-api-message-sv
            port:
              number: 5000