apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  lineConfigChannelSecretId: {{ .Values.secret.data.lineConfigChannelSecretId | b64enc }}
  lineConfigChannelClientId: {{ .Values.secret.data.lineConfigChannelClientId | b64enc }}
  lineConfigChannelChannelAccessToken: {{ .Values.secret.data.lineConfigChannelChannelAccessToken | b64enc }}