apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  lineConfigChannelSecretId: {{ .Values.secret.data.lineConfigChannelSecretId | b64enc }}
  lineConfigChannelClientId: {{ .Values.secret.data.lineConfigChannelClientId | b64enc }}
  lineConfigChannelChannelAccessToken: {{ .Values.secret.data.lineConfigChannelChannelAccessToken | b64enc }}
  objectStorageConfigServiceUrl: {{ .Values.secret.data.objectStorageConfigServiceUrl | b64enc }}
  objectStorageConfigAccessKey: {{ .Values.secret.data.objectStorageConfigAccessKey | b64enc }}
  objectStorageConfigSecretKey: {{ .Values.secret.data.objectStorageConfigSecretKey | b64enc }}
  objectStorageConfigBucketName: {{ .Values.secret.data.objectStorageConfigBucketName | b64enc }}
  {{- if eq .Release.Namespace "lmc-dev" }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 1 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 1 | b64enc }}
  {{- else }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 0 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 0 | b64enc }}
  {{- end }}