apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}-con
          image: {{ .Values.deployment.image.repo }}:{{ .Values.deployment.image.tag }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.service.ports.default }} 
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.deployment.env.aspnetCoreEnv }}
            - name: RabbitMQConfig__HostName
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: rabbitmqHost
            - name: MongoConfig__HostName
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: mongoHost
            - name: GrpcConfig__Auth__Address
              value: http://lmc-api-auth-sv.{{ .Release.Namespace }}:7000