apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if eq .Release.Namespace "lmc-dev" }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 1 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 1 | b64enc }}
  {{- else }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 0 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 0 | b64enc }}
  {{- end }}