apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec: 
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.ports.default }}
      name: default
      targetPort: {{ .Values.service.ports.default }}
      nodePort: {{ .Values.service.ports.nodePort }}
    - port: {{ .Values.service.ports.grpc }}
      name: grpc
      targetPort: {{ .Values.service.ports.grpc }}
  type: {{ .Values.service.type }}