apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      {{- if eq .Release.Namespace "default" }}
      volumes:
        - name: mongo-claim0
          persistentVolumeClaim:
            claimName: mongo-claim0
      {{- end }}
      containers:
        - name: {{ .Values.deployment.name }}-con
          image: {{ .Values.deployment.image.repo }}:{{ .Values.deployment.image.tag }}
          {{- if eq .Release.Namespace "default" }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-claim0
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.ports.default }} 
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: rootUser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: rootPass