apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rootUser: {{ .Values.secret.data.rootUser | b64enc }}
  {{- if eq .Release.Namespace "dev" }}
  rootPass: {{ index .Values.secret.data.rootPass 1 | b64enc }}
  mongodbHostname: {{ index .Values.secret.data.mongodbHostname 1 | b64enc }}
  {{- else }}
  rootPass: {{ index .Values.secret.data.rootPass 0 | b64enc }}
  mongodbHostname: {{ index .Values.secret.data.mongodbHostname 0 | b64enc }}
  {{- end }}
