apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec: 
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.ports.default }} 
      name: default
      targetPort: {{ .Values.service.ports.default }}
      {{- if eq .Release.Namespace "default" }}
      nodePort: {{ .Values.service.ports.nodePort }}
      {{- end }}
  
  {{- if eq .Release.Namespace "dev" }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}